//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientMerchantPortal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientDetails
    {
        public int CId { get; set; }
        public string OwnerName1 { get; set; }
        public string OwnerAddress1 { get; set; }
        public Nullable<int> OwnerContactNo1 { get; set; }
        public string OwnerPosition1 { get; set; }
        public string OwnerName2 { get; set; }
        public string OwnerAddress2 { get; set; }
        public Nullable<int> OwnerContactNo2 { get; set; }
        public string OwnerPosition2 { get; set; }
        public Nullable<int> BankAccount { get; set; }
    }
}
