//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientMerchantPortal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantDetail
    {
        public int MerchantId { get; set; }
        public string MerchantName { get; set; }
        public string MerchantAdress { get; set; }
        public Nullable<int> MerchantContact { get; set; }
        public Nullable<int> MerchantBankAcc { get; set; }
        public string MerchantEmail { get; set; }
    }
}
