//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientMerchantPortal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int TransId { get; set; }
        public int MerchantID { get; set; }
        public string MerchantName { get; set; }
        public int InvoiceNo { get; set; }
        public string TransDescription { get; set; }
        public Nullable<int> TransAmount { get; set; }
        public Nullable<bool> AmountStatus { get; set; }
    }
}
